general {
    lock_cmd = pidof hyprlock || hyprlock
    lock_cmd = WAYLAND_DEBUG=1 hyprlock &> ~/hyprlock.txt 2>&1
    ignore_dbus_inhibit = false
    before_sleep_cmd = loginctl lock-session
    # after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 2
}

# Dim
listener {
    timeout = 540
    on-timeout = brightnessctl -e4 -s set 55%
    on-resume = brightnessctl -r
}

# Lock
listener {
    timeout = 600
    on-timeout = hyprlock
}

# Dim
listener {
    timeout = 900
    on-timeout = brightnessctl -r && brightnessctl -e4 -s set 45%
    on-resume = brightnessctl -r
}

# Screen off
# listener {
#     timeout = 1200
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }

# Sleep
#listener {
#    timeout = 1800
#    on-timeout = systemctl suspend
#}
