# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "git",
    "rebos-git",
    "kitty-git",
    "btop",
    "yazi",
    "fastfetch",
    "hyprland-git",
    "ags-hyprpanel-git",
    "hypridle-git",
    "hyprlock-git",
    "hyprpolkitagent-git",
    "hyprsysteminfo-git",
    "hyprwayland-scanner-git",
    "hyprutils-git",
    "hyprlang-git",
    "hyprcursor-git",
    "hyprgraphics-git",
    "hyprland-qt-support-git",
    "hyprqt6engine-git",
    "hyprland-guiutils-git",
    "hyprpwcenter-git",
    "hyprshutdown-git",
    "hyprtoolkit-git",
    "hyprwire-git",
    "cava",
    "kvantum",
    "rofi-git",
    "wofi",
    "grimblast-git",
    "grim",
    "slurp",
    "wl-clipboard",
    "xdg-desktop-portal-hyprland",
    "power-profiles-daemon",
    "eza",
    "bat",
    "ripgrep",
    "fd",
    "zoxide",
    "tldr",
    "fzf",
    "thefuck",
    "swiftenv",
    "pnpm",
    "docker",
    "docker-compose",
    "lazydocker",
    "lazygit",
    "capacities-appimage",
    "antigravity",
    "vesktop-bin",
    "spotify",
    "heroic-games-launcher-bin",
    "vlc",
    "zen-browser-bin",
    "github-cli",
    "ghidra",
    "jadx",
    "uv",
    "devpod-community-bin",
    "claude-code",
    "claude-desktop-appimage",
    "beekeeper-studio-bin",
    "postman-bin",
    "proton-mail-bin",
    "proton-pass-bin",
    "wowup-cf-bin",
    "bottles",
    "lutris",
    "prismlauncher",
    "steam",
    "tailscale",
    "firewalld",
    "snapper",
    "networkmanager",
    "android-tools",
    "android-sdk",
    "android-ndk",
    "cmake",
    "gradle",
    "deno",
    "maven",
    "jdk-openjdk",
    "7zip",
    "ark",
    "dolphin",
    "kio-admin",
    "kio-extras",
    "gcr",
    "uwsm",
    "ly",
    "breeze-icons",
    "catppuccin-cursors-mocha",
    "noto-fonts-emoji",
    "ttf-input-nerd",
    "ttf-joypixels",
    "ttf-liberation",
    "ttf-nerd-fonts-symbols",
    "ttf-symbola",
    "ttf-twemoji",
    "ruff",
    "black",
    "mypy",
    "pyright",
    "python-pytest",
    "nodejs",
    "npm",
    "pnpm",
    "rust",
    "vercel",
    "zsh",
    "google-chrome",
    "aws-cli",
    "binwalk",
    "keybase",
    "mitmproxy",
    "nmap",
    "sqlmap",
    "subfinder",
    "tcpdump",
    "qwen-code",
    "playerctl",
    "opencode-bin",
    "openaudible-bin",
    "obs-studio",
    "faugus-launcher",
    "dust",
    "chezmoi",
    "linux-zen",
    "grub",
    "pavucontrol",
    "qpwgraph",
    "qt6ct",
    "python-rich",
    "python-pandas",
    "proton-vpn-gtk-app",
    "python-pydantic",
    "vicinae-bin",
    "zram-generator",
    "xorg-xmodmap",
    "touplite",
    "sof-firmware",
    "reflector",
    "python-trove-classifiers",
    "python-systemd",
    "python-pyproject-hooks",
    "perl-term-animation",
    "paru",
    "pangomm",
    "openbsd-netcat",
    "okular",
    "nvidia-open-dkms",
    "nvidia-container-toolkit",
    "nm-connection-editor",
    "namcap",
    "mips-linux-gnu-binutils",
    "lxappearance",
    "ldns",
    "intel-ucode",
    "fresh-editor-bin",
    "cups",
    "bookokrat-bin",
    "base",
    "asar",
    "alsa-utils",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
